### ISSUE TITLE
Don't retry to push location to server if Session expired

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#84]
1.5.1 F-Droid and server HEAD (21446811ab11abfb76831c654f076f53f2bfeabb) not sure what happened, I was sharing, it didn't yet lock a GPS location, I've closed the screen then this started to come, every "update interval":
```
V info.varden.hauk: .http.Packet$1.run(Packet.java:82): Received as response to packet info.varden.hauk.http.ConnectionThread$Response@c67670b
W info.varden.hauk: .service.LocationPushService$3.onFailure(LocationPushService.java:198): Failed to push location update to server
W info.varden.hauk: info.varden.hauk.http.ServerException: Session expired!
W info.varden.hauk:
W info.varden.hauk:      at info.varden.hauk.http.LocationUpdatePacket.onSuccess(LocationUpdatePacket.java:109)
W info.varden.hauk:      at info.varden.hauk.http.Packet$1.run(Packet.java:89)
W info.varden.hauk:      at info.varden.hauk.http.ConnectionThread.onPostExecute(ConnectionThread.java:114)
W info.varden.hauk:      at info.varden.hauk.http.ConnectionThread.onPostExecute(ConnectionThread.java:31)
W info.varden.hauk:      at android.os.AsyncTask.finish(Unknown Source:10)
W info.varden.hauk:      at android.os.AsyncTask.access$900(Unknown Source:0)
W info.varden.hauk:      at android.os.AsyncTask$InternalHandler.handleMessage(Unknown Source:28)
W info.varden.hauk:      at android.os.Handler.dispatchMessage(Unknown Source:19)
W info.varden.hauk:      at android.os.Looper.loop(Unknown Source:242)
W info.varden.hauk:      at android.app.ActivityThread.main(Unknown Source:98)
W info.varden.hauk:      at java.lang.reflect.Method.invoke(Native Method)
W info.varden.hauk:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
W info.varden.hauk:      at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
V info.varden.hauk: .http.Packet$1.run(Packet.java:82): Received as response to packet info.varden.hauk.http.ConnectionThread$Response@937f801
W info.varden.hauk: .service.LocationPushService$3.onFailure(LocationPushService.java:198): Failed to push location update to server
W info.varden.hauk: info.varden.hauk.http.ServerException: Session expired!
W info.varden.hauk:
W info.varden.hauk:      at info.varden.hauk.http.LocationUpdatePacket.onSuccess(LocationUpdatePacket.java:109)
W info.varden.hauk:      at info.varden.hauk.http.Packet$1.run(Packet.java:89)
W info.varden.hauk:      at info.varden.hauk.http.ConnectionThread.onPostExecute(ConnectionThread.java:114)
W info.varden.hauk:      at info.varden.hauk.http.ConnectionThread.onPostExecute(ConnectionThread.java:31)
W info.varden.hauk:      at android.os.AsyncTask.finish(Unknown Source:10)
W info.varden.hauk:      at android.os.AsyncTask.access$900(Unknown Source:0)
W info.varden.hauk:      at android.os.AsyncTask$InternalHandler.handleMessage(Unknown Source:28)
W info.varden.hauk:      at android.os.Handler.dispatchMessage(Unknown Source:19)
W info.varden.hauk:      at android.os.Looper.loop(Unknown Source:242)
W info.varden.hauk:      at android.app.ActivityThread.main(Unknown Source:98)
W info.varden.hauk:      at java.lang.reflect.Method.invoke(Native Method)
W info.varden.hauk:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
W info.varden.hauk:      at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
V info.varden.hauk: .http.Packet$1.run(Packet.java:82): Received as response to packet info.varden.hauk.http.ConnectionThread$Response@9a368e7
V info.varden.hauk: .service.LocationPushService$3.onShareListReceived(LocationPushService.java:191): Received list of shares from server
```

I've pushed the STOP sharing button to make it stop.

**Comment by bilde2910** [comment]
Related to #77 and #80

**Comment by bilde2910** [comment]
Patch will be issued in v1.5.2. Should the issue still happen in that update, feel free to reopen
